from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.db.init_db import init_db
from app.routes.meal_routes import router as meal_router
from app.routes.workout_routes import router as workout_router
from app.routes.history_routes import router as history_router
from app.routes.auth_routes import router as auth_router


# ── Lifespan (startup / shutdown) ────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Run DB table creation on startup."""
    await init_db()
    yield
    


# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Meal Planner & Workout Assistant API",
    description="Generate personalised meal plans and workout schedules powered by Gemini AI.",
    version="2.0.0",
    lifespan=lifespan,
)


# ── CORS ──────────────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Exception Handlers ────────────────────────────────────────────────────────
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    errors = {}
    for err in exc.errors():
        field = str(err["loc"][-1])
        # Use the actual error message generated by Pydantic (e.g., "String should have at least 8 characters")
        errors[field] = err["msg"]
    return JSONResponse(
        status_code=422,
        content={"status": "error", "errors": errors},
    )


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(
        status_code=exc.status_code,
        content={"status": "error", "message": exc.detail},
    )


import traceback

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    traceback.print_exc()
    return JSONResponse(
        status_code=500,
        content={"status": "error", "message": "Something went wrong. Please try again."},
    )


# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(auth_router, prefix="/api/auth", tags=["Auth"])
app.include_router(meal_router,    prefix="/api")
app.include_router(workout_router, prefix="/api")
app.include_router(history_router, prefix="/api")